"""
Tests for configuration validation.
"""
import pytest
import os
from app.config import Settings, get_settings


class TestConfigValidation:
    """Test configuration validation."""

    def setup_method(self):
        """Reset environment before each test."""
        self.original_env = dict(os.environ)
        # Clear relevant env vars
        for key in list(os.environ.keys()):
            if key.startswith(("APP_", "WHATSAPP_", "AI_", "SECRET_", "DATABASE_", "SUPABASE_")):
                del os.environ[key]

    def teardown_method(self):
        """Restore environment after test."""
        os.environ.clear()
        os.environ.update(self.original_env)

    def test_default_settings(self):
        """Test default settings values."""
        settings = Settings()
        assert settings.APP_NAME == "WhatsApp CRM SA"
        assert settings.ENVIRONMENT == "development"
        assert settings.DEBUG is True
        assert len(settings.SECRET_KEY) >= 32  # Generated by os.urandom
        assert settings.WHATSAPP_PROVIDER == "openwa"
        assert settings.DATABASE_URL == "sqlite:///./whatsapp_crm.db"

    def test_production_environment(self):
        """Test production environment detection."""
        os.environ["ENVIRONMENT"] = "production"
        settings = Settings()
        assert settings.is_production is True

    def test_secret_key_length_validation(self):
        """Test SECRET_KEY length validation."""
        os.environ["SECRET_KEY"] = "short"
        settings = Settings()
        with pytest.raises(ValueError, match="SECRET_KEY must be at least 32 characters"):
            settings.validate()

    def test_ai_provider_warning(self):
        """Test warning when no AI API keys are set."""
        # No keys set
        settings = Settings()
        # Should not raise exception but will log warning
        # Capture stdout
        import io, sys
        old_stdout = sys.stdout
        sys.stdout = buffer = io.StringIO()
        try:
            settings.validate()
            output = buffer.getvalue()
            assert "No AI API key set" in output
        finally:
            sys.stdout = old_stdout

    def test_openwa_required_fields(self):
        """Test OpenWA provider requires specific fields."""
        os.environ["WHATSAPP_PROVIDER"] = "openwa"
        # Missing OPENWA_API_KEY and OPENWA_SESSION_ID
        settings = Settings()
        with pytest.raises(ValueError) as exc_info:
            settings.validate()
        error_msg = str(exc_info.value)
        assert "OPENWA_API_KEY is required" in error_msg
        assert "OPENWA_SESSION_ID is required" in error_msg

    def test_meta_required_fields(self):
        """Test Meta provider requires specific fields."""
        os.environ["WHATSAPP_PROVIDER"] = "meta"
        # Missing META_ACCESS_TOKEN and META_PHONE_NUMBER_ID
        settings = Settings()
        with pytest.raises(ValueError) as exc_info:
            settings.validate()
        error_msg = str(exc_info.value)
        assert "META_ACCESS_TOKEN required" in error_msg
        assert "META_PHONE_NUMBER_ID required" in error_msg

    def test_twilio_required_fields(self):
        """Test Twilio provider requires specific fields."""
        os.environ["WHATSAPP_PROVIDER"] = "twilio"
        # Missing TWILIO_ACCOUNT_SID and TWILIO_WHATSAPP_FROM
        settings = Settings()
        with pytest.raises(ValueError) as exc_info:
            settings.validate()
        error_msg = str(exc_info.value)
        assert "TWILIO_ACCOUNT_SID required" in error_msg
        assert "TWILIO_WHATSAPP_FROM required" in error_msg

    def test_get_settings_caching(self):
        """Test get_settings returns cached instance."""
        settings1 = get_settings()
        settings2 = get_settings()
        assert settings1 is settings2  # Same object due to lru_cache

    def test_business_hours_settings(self):
        """Test business hours configuration."""
        os.environ["BUSINESS_HOURS_START"] = "9"
        os.environ["BUSINESS_HOURS_END"] = "17"
        settings = Settings()
        assert settings.BUSINESS_HOURS_START == 9
        assert settings.BUSINESS_HOURS_END == 17

    def test_rate_limit_settings(self):
        """Test rate limit configuration."""
        os.environ["MAX_CONVERSATIONS_PER_DAY"] = "100"
        os.environ["MAX_MESSAGES_PER_CONVERSATION"] = "25"
        os.environ["AI_RATE_LIMIT_PER_MINUTE"] = "10"
        settings = Settings()
        assert settings.MAX_CONVERSATIONS_PER_DAY == 100
        assert settings.MAX_MESSAGES_PER_CONVERSATION == 25
        assert settings.AI_RATE_LIMIT_PER_MINUTE == 10