"""
WhatsApp CRM SA — Production Setup
====================================
Interactive first-run script for SA business owners.
Sets up OpenWA → configures .env → validates everything → starts the stack.

Run:
    python scripts/setup-production.py
    # or after pip install:
    whatsapp-crm-setup
"""

import os
import sys
import uuid
import subprocess
import json
from pathlib import Path

# ── colour helpers ────────────────────────────────────────────────

def cyan(s): return f"\033[96m{s}\033[0m"
def green(s): return f"\033[92m{s}\033[0m"
def yellow(s): return f"\033[93m{s}\033[0m"
def white(s): return f"\033[97m{s}\033[0m"
def bold(s): return f"\033[1m{s}\033[0m"

# ── path helpers ─────────────────────────────────────────────────
SCRIPT_DIR  = Path(__file__).resolve().parent.parent
ENV_PATH    = SCRIPT_DIR / ".env"
EXAMPLE_PATH = SCRIPT_DIR / ".env.example"
COMPOSE_PATH = SCRIPT_DIR / "docker-compose.yml"

DOCKER_OPENWA_IMAGE  = "rmyndharis/openwa:0.1.4"
OPENWA_API_PORT      = "2785"
OPENWA_DASH_PORT     = "2886"


# ── banner ──────────────────────────────────────────────────────
def banner():
    print(f"""
{white(bold('╔═══════════════════════════════════════════════════════╗'))}
{white(bold('║'))}  {cyan(bold('📱  WhatsApp CRM SA  ·  Production Setup'))}            {white(bold('║'))}
{white(bold('║'))}  South African SMME WhatsApp CRM — OpenWA / Meta / Twilio{white(bold('║'))}
{white(bold('╠═══════════════════════════════════════════════════════╣'))}
{white(bold('║'))}  Powered by OpenWA v0.1.4 + Groq AI (free)            {white(bold('║'))}
{white(bold('╚═══════════════════════════════════════════════════════╝'))}
""")


# ── check Docker ────────────────────────────────────────────────
def check_docker() -> bool:
    try:
        subprocess.run(["docker", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


# ── load / write .env ───────────────────────────────────────────
def load_env():
    env: dict = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def save_env(env: dict):
    lines = ["# WhatsApp CRM SA — auto-generated by setup-production.py", ""]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n")
    print(f"   {green('✓')}  Saved → {ENV_PATH}")


# ── prompter ────────────────────────────────────────────────────
def prompt(label: str, default: str = "", secret: bool = False) -> str:
    if secret:
        import getpass
        v = getpass.getpass(f"   {label}: ")
    else:
        v = input(f"   {label}{f' [{default}]' if default else ''}: ").strip()
    return v or default


def ask_yesno(label: str, default: bool = True) -> bool:
    yn = "Y/n" if default else "y/N"
    v = input(f"   {label} [{yn}]: ").strip().lower()
    if not v:
        return default
    return v in ("y", "yes")


# ── OpenWA section ──────────────────────────────────────────────
def setup_openwa(env: dict) -> dict:
    print(f"\n{yellow(bold('─── OpenWA Setup ─────────────────────────────────────────'))}")
    print("OpenWA = self-hosted WhatsApp gateway (free, no Meta approval).")
    print()

    running = ask_yesno("Do you already have OpenWA running somewhere?")
    if not running:
        print()
        print("  Start it now:")
        print(f"    {cyan(f'docker run -p {OPENWA_API_PORT}:{OPENWA_API_PORT} -p {OPENWA_DASH_PORT}:{OPENWA_DASH_PORT}')}")
        print(f"    {cyan(f'  -v openwa-data:/app/data --name crm-openwa {DOCKER_OPENWA_IMAGE}')}")
        print()
        input("  Press Enter when it's running and you've scanned the QR …")

    env["WHATSAPP_PROVIDER"]      = "openwa"
    env["OPENWA_SESSION_ID"]      = prompt("OpenWA session name", default="default")
    env["OPENWA_API_URL"]         = prompt("OpenWA API URL",
                                           default=env.get("OPENWA_API_URL",
                                                           f"http://localhost:{OPENWA_API_PORT}"))
    env["OPENWA_API_KEY"]         = prompt("OpenWA API key  (from Dashboard → Settings → API Access)",
                                           secret=True)
    env["OPENWA_HMAC_KEY"]        = prompt("OpenWA HMAC key  (optional — leave blank)",
                                           default=env.get("OPENWA_HMAC_KEY", ""))
    env["OPENWA_WEBHOOK_SECRET"]  = prompt("OpenWA webhook secret  (optional — leave blank)",
                                           default=env.get("OPENWA_WEBHOOK_SECRET", ""))
    print(f"   {green('✓')}  OpenWA configured")
    return env


# ── AI section ───────────────────────────────────────────────────
def setup_ai(env: dict) -> dict:
    print(f"\n{yellow(bold('─── AI Setup ───────────────────────────────────────────'))}")
    env["AI_PROVIDER"] = "auto"
    print("AI = automatic WhatsApp replies (greetings, pricing, bookings, etc).")
    print()

    has_groq   = bool(env.get("GROQ_API_KEY")   and env["GROQ_API_KEY"] != "gsk_")
    has_or     = bool(env.get("OPENROUTER_API_KEY") and env["OPENROUTER_API_KEY"] not in ("sk-or-", "sk-or-xxx"))

    if has_groq:
        print(f"   {green('✓')}  Groq API key already in .env")
    else:
        print("  Get a free Groq API key (no credit card, 14,400 req/day):")
        print("     https://console.groq.com  →  API Keys  →  Create")
        env["GROQ_API_KEY"] = prompt("Enter your Groq API key", secret=True)

    env["OPENROUTER_API_KEY"] = prompt("OpenRouter API key  (optional fallback, blank = skip)",
                                       default=env.get("OPENROUTER_API_KEY", ""))

    print(f"   {green('✓')}  AI configured")
    return env


# ── Admin / auth ─────────────────────────────────────────────────
def setup_admin(env: dict) -> dict:
    print(f"\n{yellow(bold('─── Admin Login ─────────────────────────────────────────'))}")
    cur = env.get("ADMIN_PASSWORD", "")
    if cur and "choose" not in cur and "change" not in cur:
        print(f"   {green('✓')}  ADMIN_PASSWORD already set")
        return env
    print("The admin API (health checks, dashboard routes) is protected by JWT.")
    pw = prompt("Pick an admin password", secret=True)
    if len(pw) < 8:
        print(f"   {yellow('⚠')}  Password is very short — consider a stronger one.")
    env["ADMIN_PASSWORD"] = pw
    print(f"   {green('✓')}  Admin password set")
    return env


# ── Database ─────────────────────────────────────────────────────
def setup_database(env: dict) -> dict:
    print(f"\n{yellow(bold('─── Database ────────────────────────────────────────────'))}")
    supabase_url = env.get("DATABASE_URL", "")
    if "supabase" in supabase_url.lower() or "postgresql" in supabase_url.lower():
        print(f"   {green('✓')}  Supabase / PostgreSQL already configured")
        return env

    print("SQLite is the default (no setup needed).")
    print("For production, connect Supabase for multi-device sync:")
    print("   https://supabase.com  →  New Project  →  Connection string")
    use_supabase = ask_yesno("Connect Supabase now?")
    if use_supabase:
        url = prompt("Supabase DATABASE_URL", default="")
        if url:
            env["DATABASE_URL"] = url
            print(f"   {green('✓')}  Supabase configured")
    else:
        print(f"   {green('✓')}  Using SQLite (local, fine for single-user)")
    return env


# ── Validate ─────────────────────────────────────────────────────
def validate_env():
    errors = []
    try:
        sys.path.insert(0, str(SCRIPT_DIR))
        from app.config import get_settings
        s = get_settings()
        print(f"\n{green('✓')}  All required env vars present")
        return True, s
    except Exception as exc:
        print(f"\n{yellow('⚠')}  {exc}")
        return False, None


# ── Health check ─────────────────────────────────────────────────
def health_check(url: str = "http://localhost:8000"):
    import urllib.request
    try:
        r = urllib.request.urlopen(f"{url}/health", timeout=5)
        data = json.loads(r.read())
        return data.get("status") == "healthy"
    except Exception:
        return False


# ── Start stack ──────────────────────────────────────────────────
def start_stack(env: dict):
    if not check_docker():
        print(f"\n{yellow('⚠')}  Docker not installed — skipping stack start.")
        print(f"   Install Docker Desktop: https://www.docker.com/get-started")
        print(f"   Or deploy to Railway/Render instead.")
        return

    print(f"\n{yellow(bold('─── Starting Docker Stack ───────────────────────────────'))}")
    try:
        if str(COMPOSE_PATH).exists():
            subprocess.run(["docker", "compose", "up", "-d"], cwd=str(SCRIPT_DIR), check=True)
            print(f"   {green('✓')}  Stack started")
            print(f"   CRM API:        http://localhost:8000")
            print(f"   Swagger docs:   http://localhost:8000/docs")
            print(f"   OpenWA dashboard: http://localhost:2886")
        else:
            print(f"   {yellow('⚠')}  docker-compose.yml not found — starting CRM only")
            subprocess.run(
                ["docker", "run", "-d", "--name", "crm",
                 "-p", "8000:8000",
                 "-e", f"WHATSAPP_PROVIDER={env.get('WHATSAPP_PROVIDER','openwa')}",
                 "-e", f"OPENWA_API_URL={env.get('OPENWA_API_URL','')}",
                 "-e", f"OPENWA_API_KEY={env.get('OPENWA_API_KEY','')}",
                 "-e", f"GROQ_API_KEY={env.get('GROQ_API_KEY','')}",
                 "python:3.12-slim",
                 "sh", "-c",
                 "pip install -q fastapi uvicorn[standard] requests apscheduler"
                 " sqlalchemy asyncpg pyjwt httpx phonenumbers"
                 " && uvicorn app.main:app --host 0.0.0.0 --port 8000"],
                check=False,
            )
    except subprocess.CalledProcessError as exc:
        print(f"   {yellow('⚠')}  Stack start failed ({exc}). Run manually: docker compose up -d")


# ── Next steps ───────────────────────────────────────────────────
def print_next_steps(env: dict):
    openwa_url = env.get("OPENWA_API_URL", "http://localhost:2785").rstrip("/")
    print(f"""
{yellow(bold('─── Next Steps ─────────────────────────────────────────────'))}
{green('1')}. Scan QR on OpenWA dashboard  →  {cyan(openwa_url.replace('http://localhost:2785','http://localhost:2886'))}
    (create session → link device)

{green('2')}. Test a message:
    curl http://localhost:8000/health

{green('3')}. Admin login (get JWT token):
    curl -X POST http://localhost:8000/api/auth/login \\
         -H 'Content-Type: application/json' \\
         -d '{{"password":"{env.get("ADMIN_PASSWORD","YOUR_PASSWORD")}"}}'

{green('4')}. Read the client guide:
    cat CLIENT-ONBOARDING.md

{green('5')}. Deploy to production:
    ./deploy.sh railway    (or render, or docker)
""")


# ── MAIN ─────────────────────────────────────────────────────────
def main():
    banner()
    env = load_env()

    env = setup_openwa(env)
    env = setup_ai(env)
    env = setup_admin(env)
    env = setup_database(env)

    save_env(env)

    ok_, _ = validate_env()

    if "docker" not in env and check_docker():
        start_now = ask_yesno("Start the Docker stack now?", default=True)
        if start_now:
            start_stack(env)
            import time as _t
            _t.sleep(5)
            ok_ = health_check()

    print(bold(green("\n✓  Setup complete!")) if ok_ else bold(yellow("\n⚠  Done — fix the errors above before starting.")))
    print_next_steps(env)


if __name__ == "__main__":
    main()
